//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildTigerThai.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Menu_ID { get; set; }
        public int Menu1 { get; set; }
        public int Section_ID { get; set; }
        public int SectionPrecedence { get; set; }
        public string MenuName { get; set; }
    
        public virtual Section Section { get; set; }
    }
}
