//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildTigerThai.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsToSpecial
    {
        public int ProductToSpecial_ID { get; set; }
        public int Product_ID { get; set; }
        public int Special_ID { get; set; }
        public decimal SpecialPrice { get; set; }
        public bool Active { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Special Special { get; set; }
    }
}
