//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildTigerThai.DATA.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ProductsToSpecial
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ProductToSpecial_ID { get; set; }
        [Display(Name = "Product")]
        public int Product_ID { get; set; }
        [Display(Name = "Special")]
        public int Special_ID { get; set; }
        [Display(Name = "Special Price")]
        [DisplayFormat(NullDisplayText = "N/A", DataFormatString = "{0:c}")]
        public decimal SpecialPrice { get; set; }
        public bool Active { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Special Special { get; set; }
    }
}
