//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildTigerThai.DATA.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Special
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Special()
        {
            this.ProductsToSpecials = new HashSet<ProductsToSpecial>();
        }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Special_ID { get; set; }
        [Display(Name = "Special Name")]
        [StringLength(100, ErrorMessage = "Should not exceed 100 characters")]
        [Required(ErrorMessage = "*Required")]
        public string Name { get; set; }
        [Display(Name = "Special Beginning Date")]
        [DisplayFormat(NullDisplayText = "N/A", DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> SpecialBeginningDate { get; set; }
        [Display(Name = "Special End Date")]
        [DisplayFormat(NullDisplayText = "N/A", DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> SpecialEndDate { get; set; }
        [Display(Name = "Special Start Time")]
        [StringLength(100, ErrorMessage = "Should not exceed 100 characters")]
        public string SpecialStartTime { get; set; }
        [Display(Name = "Special End Time")]
        [StringLength(100, ErrorMessage = "Should not exceed 100 characters")]
        public string SpecialEndTime { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsToSpecial> ProductsToSpecials { get; set; }
    }
}
