//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildTigerThai.DATA.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Special
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Special()
        {
            this.ProductsToSpecials = new HashSet<ProductsToSpecial>();
        }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Special_ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> SpecialBeginningDate { get; set; }
        public Nullable<System.DateTime> SpecialEndDate { get; set; }
        public string SpecialStartTime { get; set; }
        public string SpecialEndTime { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsToSpecial> ProductsToSpecials { get; set; }
    }
}
