//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildTigerThai.DATA.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WildTigerThaiDBEntities : DbContext
    {
        public WildTigerThaiDBEntities()
            : base("name=WildTigerThaiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<PhotoType> PhotoTypes { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductsToSection> ProductsToSections { get; set; }
        public virtual DbSet<ProductsToSpecial> ProductsToSpecials { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Special> Specials { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
    }
}
